#!/bin/bash

# (make sure we can access the parser package)
export CLASSPATH=../../src:$CLASSPATH

jython ../../src/netlister.py -i l1a_mk1.v \
    -l "../../lib/l1a-custom.lib" \
    -l "../../lib/cpu.lib" \
    -l "../../lib/rcl.lib" \
    -l "../../lib/memory.lib" \
    -l "../../lib/74series.lib" \
    -l "../../lib/switches.lib" \
    -f net \
    -o l1a_mk1.net

jython ../../src/netlister.py -i l1a_mk1.v \
    -l "../../lib/l1a-custom.lib" \
    -l "../../lib/cpu.lib" \
    -l "../../lib/rcl.lib" \
    -l "../../lib/memory.lib" \
    -l "../../lib/74series.lib" \
    -l "../../lib/switches.lib" \
    -f scr \
    -o l1a_mk1.scr \
    -t l1a_mk1_footer.scr 
