#!/bin/bash

# (make sure we can access the pSrser package)
export CLASSPATH=../../src:$CLASSPATH
export TERM=xterm

NLIST_PATH=../..

jython ${NLIST_PATH}/src/netlister.py -i l1b_mk1.v \
    -l "${NLIST_PATH}/lib/l1b-custom.lib" \
    -l "${NLIST_PATH}/lib/l1a-custom.lib" \
    -l "${NLIST_PATH}/lib/xilinx.lib" \
    -l "${NLIST_PATH}/lib/cpu.lib" \
    -l "${NLIST_PATH}/lib/rcl.lib" \
    -l "${NLIST_PATH}/lib/i2c.lib" \
    -l "${NLIST_PATH}/lib/memory.lib" \
    -l "${NLIST_PATH}/lib/74series.lib" \
    -l "${NLIST_PATH}/lib/switches.lib" \
    -l "${NLIST_PATH}/lib/idc_connectors.lib" \
    -f scr \
    -o l1b_mk1.scr \
    -t l1b_mk1_footer.scr

jython ${NLIST_PATH}/src/netlister.py -i l1b_mk1.v \
    -l "${NLIST_PATH}/lib/l1b-custom.lib" \
    -l "${NLIST_PATH}/lib/l1a-custom.lib" \
    -l "${NLIST_PATH}/lib/xilinx.lib" \
    -l "${NLIST_PATH}/lib/cpu.lib" \
    -l "${NLIST_PATH}/lib/rcl.lib" \
    -l "${NLIST_PATH}/lib/i2c.lib" \
    -l "${NLIST_PATH}/lib/memory.lib" \
    -l "${NLIST_PATH}/lib/74series.lib" \
    -l "${NLIST_PATH}/lib/switches.lib" \
    -l "${NLIST_PATH}/lib/idc_connectors.lib" \
    -o l1b_mk1.net \
    -f net
